CREATE TABLE account (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
);

-------------------------------

CREATE TABLE account_balance (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    account_id BIGINT NOT NULL,
    balance_type VARCHAR(255) NOT NULL,
    balance DECIMAL(19, 4) NOT NULL,

    FOREIGN KEY (account_id) REFERENCES account(id)
);

CREATE INDEX idx_account_balance_account_id ON account_balance(account_id);

-------------------------------

CREATE TABLE transaction_payload (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    account_id BIGINT NOT NULL,
    amount DECIMAL(19, 4) NOT NULL,
    merchant_category VARCHAR(255),
    name_address VARCHAR(255),

    FOREIGN KEY (account_id) REFERENCES account(id)
);

CREATE INDEX idx_transaction_payload_account_id ON transaction_payload(account_id);
